/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "cmsis_os.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include <stdio.h>

/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */
typedef struct {
    uint8_t dataID;
    int32_t DataValue;
} Data_t;
/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
#define QUEUE_SIZE 5
#define TASK1_PRIORITY osPriorityNormal
#define TASK2_PRIORITY osPriorityNormal

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
osThreadId_t ExampleTask1Handle;
osThreadId_t ExampleTask2Handle;
osMessageQueueId_t Queue1Handle;

/* USER CODE BEGIN PV */
uint8_t G_DataID;
int32_t G_DataValue;
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
void ExampleTask1(void *argument);
void ExampleTask2(void *argument);

/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config();

  /* Initialize all configured peripherals */
  MX_GPIO_Init();

  /* USER CODE BEGIN 2 */

  /* USER CODE END 2 */

  /* Init scheduler */
  osKernelInitialize();

  /* Create the queue(s) */
  /* definition and creation of Queue1 */
  const osMessageQueueAttr_t Queue1_attributes = {
    .name = "Queue1"
  };
  Queue1Handle = osMessageQueueNew (QUEUE_SIZE, sizeof(Data_t), &Queue1_attributes);

  /* Create the thread(s) */
  /* definition and creation of ExampleTask1 */
  const osThreadAttr_t ExampleTask1_attributes = {
    .name = "ExampleTask1",
    .priority = (osPriority_t) TASK1_PRIORITY,
    .stack_size = 128 * 4
  };
  ExampleTask1Handle = osThreadNew(ExampleTask1, NULL, &ExampleTask1_attributes);

  /* definition and creation of ExampleTask2 */
  const osThreadAttr_t ExampleTask2_attributes = {
    .name = "ExampleTask2",
    .priority = (osPriority_t) TASK2_PRIORITY,
    .stack_size = 128 * 4
  };
  ExampleTask2Handle = osThreadNew(ExampleTask2, NULL, &ExampleTask2_attributes);

  /* Start scheduler */
  osKernelStart();

  /* We should never get here as control is now taken by the scheduler */
  /* Infinite loop */
  while (1)
  {
    /* USER CODE BEGIN WHILE */

    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  /* (System clock configuration generated by STM32CubeMX) */
}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  /* (GPIO initialization generated by STM32CubeMX) */
}

/* USER CODE BEGIN 4 */

/**
  * @brief  Function implementing the ExampleTask1 thread.
  * @param  argument: Not used
  * @retval None
  */
void ExampleTask1(void *argument)
{
  Data_t dataToSend;

  /* Infinite loop */
  for(;;)
  {
    // Populate the structure members with global variables
    dataToSend.dataID = G_DataID;
    dataToSend.DataValue = G_DataValue;

    // Send data to the queue
    if (osMessageQueuePut(Queue1Handle, &dataToSend, 0, osWaitForever) != osOK) {
        printf("Failed to send to queue.\n");
    }

    // Delay for 500ms
    osDelay(500);
  }
}

/**
  * @brief  Function implementing the ExampleTask2 thread.
  * @param  argument: Not used
  * @retval None
  */
void ExampleTask2(void *argument)
{
  Data_t receivedData;
  osThreadId_t currentTaskHandle = osThreadGetId();
  osPriority_t originalPriority = osThreadGetPriority(currentTaskHandle);

  /* Infinite loop */
  for(;;)
  {
    // Receive data from the queue
    if (osMessageQueueGet(Queue1Handle, &receivedData, NULL, osWaitForever) == osOK) {
        // Print the received data
        printf("Received dataID: %d, DataValue: %d\n", receivedData.dataID, receivedData.DataValue);

        // Apply the specified logic
        if (receivedData.dataID == 0) {
            osThreadTerminate(currentTaskHandle); // Delete ExampleTask2
        } else if (receivedData.dataID == 1) {
            // Allow processing of DataValue
            if (receivedData.DataValue == 0) {
                // Increase the priority of ExampleTask2 by 2
                osThreadSetPriority(currentTaskHandle, (osPriority_t)(originalPriority + 2));
            } else if (receivedData.DataValue == 1) {
                // Decrease the priority of ExampleTask2 if previously increased
                osThreadSetPriority(currentTaskHandle, originalPriority);
            } else if (receivedData.DataValue == 2) {
                osThreadTerminate(currentTaskHandle); // Delete ExampleTask2
            }
        }
    }
  }
}

/* USER CODE END 4 */
